### ISSUE TITLE
Small typo on the readme.html

### ISSUE THREAD

**Issue by JoshGalvin** [MozVR/MozVR.com-issues#1]
Direct to Rift support is currently buggy, and setting the displlays to be unique works, but requires dragging the browser window to the HMD display, which becomes awkward.

displlays -> displays.

**Comment by caseyyee** [comment]
This is a Mac only issue.  On PC, the screen moves automatically as you enter VR mode to the Rift display.    

Behavior definitely could use some adjustments, but this work needs to be done in platform and can't be addressed in content by the site.
