### ISSUE TITLE
Firefox-36.0a1.en-US.mac.dmg broken

### ISSUE THREAD

**Issue by Ommane** [MozVR/MozVR.com-issues#10]
I am on a late 2013 Macbook Pro running OS X 10.9.5
When I download Firefox nightly Firefox-36.0a1.en-US.mac.dmg with either Safari or Chrome Canary and try to open it I get a message that it is broken and to eject the disk image.

Regards
-Sam

**Comment by RMKD** [comment]
+1 on this issue. Security and Privacy settings may be restricted even from Admin users to prevent changing the "allow apps" setting. OSX 10.9.5

![allow-apps-blocked](https://cloud.githubusercontent.com/assets/334410/6286762/eef7110e-b8d8-11e4-9f92-8c3c4aa9e010.png)

**Comment by RMKD** [comment]
if your Security and Privacy settings are restricted as above, running from the command line seems to work: 
```
./FirefoxNightly.app/Contents/MacOS/firefox
```

**Comment by caseyyee** [comment]
Everyone should now be using Firefox Nightly + VR Add on
http://mozvr.com/downloads/
