### ISSUE TITLE
Windows display setup instructions are confusing

### ISSUE THREAD

**Issue by brianpeiris** [MozVR/MozVR.com-issues#13]
The instructions are currently:

> **Display > Screen Resolution**
> Orientation: 90° rotation
> Multiple displays: Extended desktop
> **Display > Screen Resolution**
> Refresh: 60Hz

Should read:

> **Display > Screen Resolution**
> Orientation: Landscape (flipped)
> Multiple displays: Extend these displays
> **Advanced Settings > Monitor > Monitor Settings**
> Screen refresh rate: 60 Hertz

The orientation listed in the screenshot is incorrect as well. Here is a corrected version and a screenshot of the refresh rate setting dialog:  
 
![mozvrresolution](https://cloud.githubusercontent.com/assets/79419/6479654/eb898f00-c216-11e4-9b0c-cd70cb0493af.png)

![mozvrrefresh](https://cloud.githubusercontent.com/assets/79419/6479512/728bf220-c214-11e4-82e9-7141e951d968.png)

**Comment by caseyyee** [comment]
Update instructions on site to reflect.

**Comment by jcarpenter** [comment]
Thanks for flagging this Brian, and especially for going the distance and providing images :) I wrote the original instructions per what I was seeing on my work PC, but I'm not a Windows guy so it's possible my laptop / install is idiosyncratic. We're pushing an update this evening with the new copy and images.

**Comment by brianpeiris** [comment]
Nice! Glad I could help.

**Comment by caseyyee** [comment]
Changes are deployed and up on site.
