### ISSUE TITLE
eleVR play button needs to be disabled

### ISSUE THREAD

**Issue by hawksley** [MozVR/MozVR.com-issues#3]
eleVR by default when the video finishes pops up a play button in the middle of the screen, which is now overlaying the whole mozvr.com demo. That whole functionality should probably be removed. 

In particular,

      
      <div id="left-load" class="left">
        <div id="title-l" class="title">Loading Video...</div>
        <div id="message-l" class="message">Try WASD + Q/E</div>
      </div>
      <div id="right-load" class="right">
        <div id="title-r" class="title">Loading Video...</div>
        <div id="message-r" class="message">Try WASD + Q/E</div>
      </div>
      <div id="left-play" class="left" style="display:none;">
        <a id="play-l" class="large-play fa fa-play fa-5x"></a>
      </div>
      <div id="right-play" class="right" style="display:none;">
        <a id="play-r" class="large-play fa fa-play fa-5x"></a>
      </div>

should all be removed from the html, and any corresponding js that references it should be removed as well.

It might also be nice if it either looped the video (really easy) or popped up the menu/returned you to home when the video completes (probably pretty easy too. You can use the same trigger that is currently being used to show those play buttons.)

**Comment by caseyyee** [comment]
Addressed in Polar sea repo
