### ISSUE TITLE
Screen goes black after 10 seconds

### ISSUE THREAD

**Issue by sgehrman** [MozVR/MozVR.com-issues#4]
Looks nice, but before I can do anything the screen goes black.  Also, didn't work in direct mode.  Windows 8.1.

**Comment by PyryM** [comment]
Same problem here. Also happens in riftsketch (https://github.com/brianpeiris/RiftSketch). The "allow fullscreen" overlay and mouse cursor are still visible even after the screen goes black.

The blackout problem doesn't happen in firefox vr build 34.0a1.

**Comment by brianpeiris** [comment]
I think this has been resolved in the latest Nightly builds.
