### ISSUE TITLE
Splash has overlapping text/graphic when screen is small-ish

### ISSUE THREAD

**Issue by gordonbrander** [MozVR/MozVR.com-issues#6]
Example:

![screen shot 2014-11-11 at 16 23 57](https://cloud.githubusercontent.com/assets/58421/5003195/2732641a-69bf-11e4-93b6-5109c38970e0.png)

Unfortunately when browser window is smaller, text and image overlap in a way that makes them both unreadable. Unfortunate, because the text tells me what to do next (download VR build).

I think we could cure this with a little bit of media query magic.

**Comment by brianpeiris** [comment]
This has been resolved with the new design.
