### ISSUE TITLE
[Windows] Setting Rift DK2 display mode to Portrait as instructed gives rotated image

### ISSUE THREAD

**Issue by cglwn** [MozVR/MozVR.com-issues#9]
It seems that Landscape(flipped) is the option that works for me.
![capture](https://cloud.githubusercontent.com/assets/1919795/5161175/7f5f9e28-736f-11e4-8f97-e30dfeec8ad8.PNG)

**Comment by brianpeiris** [comment]
Yeah, seems the instructions are incorrect. Mentioned in #13 as well.

**Comment by caseyyee** [comment]
Keeping it down to 1 issue.   See #13
